// ──── DOM Cache ────
export const dom = {
    cvs: document.getElementById('hexCanvas'),
    wrap: document.getElementById('canvas-wrap'),

    sidebarToggle: document.getElementById('sidebarToggle'),
    fullscreenBtn: document.getElementById('fullscreenBtn'),
    cursor: document.getElementById('lum-cursor'),

    zoomLabel: document.getElementById('zoomLabel'),
    zoomIn: document.getElementById('zoomIn'),
    zoomOut: document.getElementById('zoomOut'),
    gridToggle: document.getElementById('gridToggle'),
    uploadZone: document.getElementById('uploadZone'),
    fileInput: document.getElementById('fileInput'),
    fileName: document.getElementById('fileName'),
    editorPanel: document.getElementById('editorPanel'),
    resetTexBtn: document.getElementById('resetTexBtn'),
    resetAllRot: document.getElementById('resetAllRot'),
    randAnglesBtn: document.getElementById('randAnglesBtn'),
    randLineColorsBtn: document.getElementById('randLineColorsBtn'),
    randGradColorsBtn: document.getElementById('randGradColorsBtn'),
    markersToggle: document.getElementById('markersToggle'),
    cancelEd: document.getElementById('cancelEd'),
    applyEd: document.getElementById('applyEd'),
    toast: document.getElementById('toast'),
    previewCanvas: document.getElementById('previewCanvas'),
    sRot: document.getElementById('sRot'),
    sScale: document.getElementById('sScale'),
    sSX: document.getElementById('sSX'),
    sSY: document.getElementById('sSY'),
    sOX: document.getElementById('sOX'),
    sOY: document.getElementById('sOY'),
    vRot: document.getElementById('vRot'),
    vScale: document.getElementById('vScale'),
    vSX: document.getElementById('vSX'),
    vSY: document.getElementById('vSY'),
    vOX: document.getElementById('vOX'),
    vOY: document.getElementById('vOY'),
    gradientList: document.getElementById('gradientList'),
    addMarkerBtn: document.getElementById('addMarkerBtn'),
    curveList: document.getElementById('curveList'),
    addCurveBtn: document.getElementById('addCurveBtn'),

    exportBtn: document.getElementById('exportBtn'),
    exportOverlay: document.getElementById('exportOverlay'),
    exportFrame: document.getElementById('exportFrame'),
    exportMenu: document.getElementById('exportMenu'),
    exportBackdrop: document.getElementById('exportBackdrop'),
    exportW: document.getElementById('exportW'),
    exportH: document.getElementById('exportH'),
    exportPngBtn: document.getElementById('exportPngBtn'),
    exportEmbedBtn: document.getElementById('exportEmbedBtn'),
    embedCodeWrap: document.getElementById('embedCodeWrap'),
    embedCode: document.getElementById('embedCode'),
    copyEmbedBtn: document.getElementById('copyEmbedBtn'),

    closeExportBtn: document.getElementById('closeExportBtn'),
    exportImageBtn: document.getElementById('exportImageBtn'),
    exportEmbedBtn: document.getElementById('exportEmbedBtn'),
    imageExportWrap: document.getElementById('imageExportWrap'),
    fmtPngBtn: document.getElementById('fmtPngBtn'),
    fmtPdfBtn: document.getElementById('fmtPdfBtn'),
    fmtSvgBtn: document.getElementById('fmtSvgBtn'),
    aspectLockBtn: document.getElementById('aspectLockBtn'),
    exportSide: document.getElementById('exportSide'),

    statCurves: document.getElementById('statCurves'),
    statColors: document.getElementById('statColors'),
    statCurvesWrap: document.getElementById('statCurvesWrap'),
    statColorsWrap: document.getElementById('statColorsWrap'),
    ghLink: document.getElementById('ghLink'),

    sCurveW: document.getElementById('sCurveW'),
    vCurveW: document.getElementById('vCurveW'),

    sAlterTiles: document.getElementById('sAlterTiles'),
    vAlterTiles: document.getElementById('vAlterTiles'),

    bgStarsToggle: document.getElementById('bgStarsToggle'),
    markersToggle: document.getElementById('markersToggle'),
    flowToggle: document.getElementById('flowToggle'),
    liveTwistsToggle: document.getElementById('liveTwistsToggle'),
    inertiaToggle: document.getElementById('inertiaToggle'),

    sidebar: document.querySelector('.sidebar'),
    sidebarToggle: document.getElementById('sidebarToggle'),
    fullscreenBtn: document.getElementById('fullscreenBtn'),
};